### ISSUE TITLE
This doesn't work with svelte/astro

### ISSUE THREAD

**Issue by Fischchen** [beyonk-group/gdpr-cookie-consent-banner#46] opened 2023-01-16 18:07 UTC
When trying to use this with Astro, It never shows the banner and just the little cookie in the corner.
Furthermore, it says Cannot find name 'initAnalytics'

Doses this just not work with Astro or have I done something wrong?
I put the svelte object in the body.

I have this in my body:
```Astro
<GdprBanner cookieName="foo" description="bar" on:analytics={initAnalytics} />

<script>
  import '@beyonk/gdpr-cookie-consent-banner/dist/style.css' // optional, you can also define your own styles
  import GdprBanner from '@beyonk/gdpr-cookie-consent-banner'

  function initAnalytics () {
    // do something with segment.io or google analytics etc
    alert('analytics enabled')
  }
</script>
```

**Comment by antony** [comment] 2023-06-12 15:33
Hey @Fischchen - I've never used Astro, so I can't be sure what the problem is here.

It seems like everything that you've done is right, so I'm puzzled.

**Comment by antony** [comment] 2023-09-07 09:37
Hey @Fischchen - since I've not heard from you, and I don't use Astro, I'm going to close this.

Feel free to reopen if you have more info.

**Closed by antony** 2023-09-07 09:37 UTC
